language: node_js
dist: trusty
sudo: required
node_js: stable
services:
  - docker
install:
  - npm install -g bower
  - make install
script:
  - make compile-contracts
  - make build-dapp
  - docker run -d -p 8545:8545 foamspace/cliquebait:latest
  - sleep 10
  - make test-dapp
